server:
  error:
    include-message: always
  port: 80
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-west-2.amazonaws.com/${USER_POOL_ID}

  application:
    name: cluvr
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  batch:
    job:
      enabled: false  # 앱 실행 시 자동 실행 방지 (직접 JobLauncher 사용하기 위함)
    jdbc:
      initialize-schema: never

  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        highlight_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cluvrmails@gmail.com
    password: ${app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
jwt:
  secret:
    key: ${jwt.secret.key}
app:
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*
      - http://localhost:63342
      - http://localhost:3000
      - http://54.200.146.243


cognito:
  userPoolId: ${USER_POOL_ID}
  clientId: ${CLIENT_ID}
  jwkSetUri: https://cognito-idp.us-west-2.amazonaws.com/${USER_POOL_ID}/.well-known/jwks.json
  clientSecret: ${CLIENT_SECRET}

cloud:
  aws:
    region:
      static: us-west-2
    credentials:
      access-key: ${ACCESS_AWS}
      secret-key: ${SECRET_AWS}

logging:
  level:
    root: INFO
    software.amazon.awssdk: DEBUG
    com.amazonaws: DEBUG
    com.example.cluvrapi: DEBUG
