#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: root
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  redis:
#    enabled: false
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#jwt:
#  secret:
#    key: test-jwt-secret-key
#app:
#  cors:
#    allowed-origins:
#      - http://localhost:*
#      - http://127.0.0.1:*
#      - http://localhost:63342
#      - http://localhost:3000
#      - http://54.200.146.243
